<a href="https://colab.research.google.com/github/YJU-KimJeongSu/YJU-KimJeongSu/blob/main/AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%tensorflow_version

Currently selected TF version: 2.x
Available versions:
* 1.x
* 2.x


In [2]:
import keras

In [3]:
import numpy

In [4]:
import numpy as np

In [7]:
stArray = np.array([1, 3, 5, 7, 9])

In [8]:
stArray

array([1, 3, 5, 7, 9])

In [9]:
stArray.shape

(5,)

In [5]:
stArray2 = np.array([[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]])

In [6]:
stArray2

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [7]:
stArray2.shape

(2, 5)

In [8]:
stArray2.reshape(5, 2)

array([[ 1,  3],
       [ 5,  7],
       [ 9,  2],
       [ 4,  6],
       [ 8, 10]])